### ISSUE TITLE
Teacher Review Week 4

### ISSUE THREAD

**Issue by purplebears321** [zenxha/m22-2-blackpink-but-specifically-Rose#24]

**Comment by jm1021** [comment]
Unit 4 test correct collab.  Readme focus.  Had some TODO and In-progress.  Practice Java on REPL.  Nice break down on assignments.   1.0

**Comment by akprathipati** [comment]
Allen,
Did the video "alone". Which represents team points are 1.5 of 2 with video. Make sure its a group effort next time
Individually, I see tickets with Check Box completion in In progress. Link in README has  tangibles and everything looks great!  2/2
Journal I see test score and notes are excellent  5/5
9.5/10 + .25 for doing video
total score:**9.75**
Great job!

**Comment by akprathipati** [comment]
Komay,
Did the video "alone". Which represents team points are 1.5 of 2 with video. Make sure its a group effort next time
Individually, I see tickets with Check Box completion in In progress. Link in README has  tangibles and everything looks great!  2/2
Journal I see test score and notes are excellent  5/5
9.5/10  
total score:**9.5**
Great job!

**Comment by akprathipati** [comment]
Charlie,
Did the video "alone". Which represents team points are 1.5 of 2 with video. Make sure its a group effort next time
Individually, I see tickets with Check Box completion in In progress. Link in README has tangibles and everything looks great! 2/2
Journal I see test score and notes are excellent 5/5
9.5/10
total score:9.5
Great job!

**Comment by akprathipati** [comment]
Charlie,
Did the video "alone". Which represents team points are 1.5 of 2 with video. Make sure its a group effort next time
Individually, I see tickets with Check Box completion in In progress. Link in README has tangibles and everything looks great! 2/2
Journal I see test score and notes are excellent 5/5
9.5/10
total score:9.5
Great job!
