### ISSUE TITLE
Review Week 7

### ISSUE THREAD

**Issue by purplebears321** [zenxha/m22-2-blackpink-but-specifically-Rose#35]

**Comment by jm1021** [comment]
Scrum board is a little bit of a mess.  Showed some research.  Maintained an action for Units.   Some secondary thinking shown on Frontend, similar to Model.   Missing list of images discussion.   

.85/1

**Comment by elw55555** [comment]
**TEAM: 4.5/5**
- Video is 2 minutes, easy to understand and demonstrates everyone's contributions
_Modeling Checkpoint:_
Positive:
- Extended base image display on home page by extending array image list in controller for grayscale [here](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/blob/3134d552c2f135a0e2d081cc207b3f3265abbc10/src/main/java/com/example/sping_portfolio/controllers/GrascaleController.java#L11-L60)
- Demonstration of utilization of 10 images onto grayscale website by implementing the pngs into [static directory](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/tree/main/src/main/resources/static/images)
- [Front end ticket](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/projects/1#card-69143266) showed good tangibles to easily explain the process Allen and Komay worked on to improve the front end grayscale
Negative:
- Current web redirection in controller redirects to the correct template file, though the page often enters a 404 page which requires some fixing, although the steps to the solution can be seen and only requires a bit of a push to fully get running, although it is an area to work on
**Individual**
_Charlie:_ 
- 1.25/1.5 Contribution to the project is seen on model improvements, but just forgor to [update tickets](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/projects/1#card-69234010) on the model improvement scrum board with tangibles
- 1.5/1.5 notes and journal are up to date with corrections
_Tanmay:_ 
- 1.25/1.5 Contribution to the project was also on model improvements, collaborated with Charlie but just forgot to update the [ticket](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/projects/1#card-69234010) with tangibles
- 1.5/1.5 notes and journal are up to date with corrections
_Komay:_ 
- 1.5/1.5, Contribution to project can be seen clearly with control improvements, with a [ticket with tangibles](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/projects/1#card-69233716)
- 1.5/1.5 notes and journal are up to date with corrections
_Allen:_ 
- 1.5/1.5, Contribution to project can be clearly seen with updated [front end ticket with tangibles](https://github.com/zenxha/m22-2-blackpink-but-specifically-Rose/projects/1#card-69143266)
- 1.5/1.5 notes and journal are up to date and with corrections

**Comment by jm1021** [comment]
Really hard for me to see any modeling improvements.  -.25 from scores provided, plus another -.15 from planning which may be why little was done.
